# Generated by Django 5.1.6 on 2025-02-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created_at'),
        ('posts', '0002_rename_body_post_content_alter_post_title'),
    ]

    operations = [
    ]
